/**
 * Drizzle Agent Registry
 *
 * Implements AgentRegistry by querying the `agents` table.
 */

import { db } from './connection.js';
import { agents } from './schema.js';
import { eq } from 'drizzle-orm';
import type { AgentRegistry, AgentRegistryEntry, AgentRegistryInput } from '@mcai/orchestrator';

export class DrizzleAgentRegistry implements AgentRegistry {
  async loadAgent(id: string): Promise<AgentRegistryEntry | null> {
    const result = await db
      .select()
      .from(agents)
      .where(eq(agents.id, id))
      .limit(1);

    if (result.length === 0) return null;

    const row = result[0];
    return {
      id: row.id,
      name: row.name,
      description: row.description,
      model: row.model,
      provider: row.provider,
      system_prompt: row.system_prompt,
      temperature: row.temperature,
      max_steps: row.max_steps,
      tools: row.tools,
      permissions: row.permissions,
    };
  }

  /**
   * Register a new agent and return its auto-generated UUID.
   *
   * The `id` is generated by Postgres via `defaultRandom()`.
   */
  async registerAgent(input: AgentRegistryInput): Promise<string> {
    const result = await db
      .insert(agents)
      .values({
        name: input.name,
        description: input.description,
        model: input.model,
        provider: input.provider,
        system_prompt: input.system_prompt,
        temperature: input.temperature,
        max_steps: input.max_steps,
        tools: input.tools,
        permissions: {
          sandbox: input.permissions?.sandbox ?? false,
          read_keys: input.permissions?.read_keys ?? [],
          write_keys: input.permissions?.write_keys ?? [],
          ...(input.permissions?.budget_usd !== undefined ? { budget_usd: input.permissions.budget_usd } : {}),
        },
      })
      .returning({ id: agents.id });

    return result[0].id;
  }
}
