/**
 * Event Sourcing Types
 *
 * Defines the shape of workflow events used for durable execution.
 * Events are appended to an immutable log during workflow execution
 * and replayed through pure reducers during crash recovery.
 *
 * @module types/event
 */

import { z } from 'zod';
import { ActionSchema } from './state.js';

/**
 * The types of events that can be recorded in the event log.
 *
 * - `workflow_started`    — `run()` was invoked (first event in every run)
 * - `node_started`        — a node began execution
 * - `action_dispatched`   — an agent/node returned an Action (contains LLM response)
 * - `internal_dispatched` — `dispatchInternal()` was called (`_init`, `_advance`, `_complete`, etc.)
 * - `state_persisted`     — state snapshot was saved (marker only, no payload)
 */
export const EventTypeSchema = z.enum([
  'workflow_started',
  'node_started',
  'action_dispatched',
  'internal_dispatched',
  'state_persisted',
]);

export type EventType = z.infer<typeof EventTypeSchema>;

/**
 * A single event in the workflow event log.
 *
 * The combination of `run_id` + `sequence_id` uniquely identifies an event
 * and defines the replay order. Events with `action` payloads contain the
 * full serialized Action (including LLM responses) so that replay can skip
 * expensive re-computation.
 */
export const WorkflowEventSchema = z.object({
  /** Unique event identifier. */
  id: z.string().uuid(),
  /** Run this event belongs to. */
  run_id: z.string().uuid(),
  /** Monotonically increasing sequence within the run. */
  sequence_id: z.number().int().nonnegative(),
  /** Event category. */
  event_type: EventTypeSchema,
  /** Node that produced this event (absent for run-level events). */
  node_id: z.string().optional(),
  /** Serialized action payload (for `action_dispatched` events). */
  action: ActionSchema.optional(),
  /** Internal event type (for `internal_dispatched` events). */
  internal_type: z.string().optional(),
  /** Internal payload (for `internal_dispatched` events). */
  internal_payload: z.record(z.string(), z.unknown()).optional(),
  /** When the event was recorded. */
  created_at: z.date(),
});

export type WorkflowEvent = z.infer<typeof WorkflowEventSchema>;

/**
 * Input shape for appending a new event.
 *
 * `id` and `created_at` are auto-generated by the event log writer.
 */
export type NewWorkflowEvent = Omit<WorkflowEvent, 'id' | 'created_at'>;
